name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Login to Github Container Registry
      run: echo ${{secrets.TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{github.actor}}/traefik-frontend:latest
      
    - name: Push to Github Container Registry
      run: docker push ghcr.io/${{github.actor}}/traefik-frontend:latest
